### ISSUE TITLE
same interest

### ISSUE THREAD

**Issue by yxh02** [Yutong-Zhou-cv/A-Text_to_Image-zoo#1]
hi,are you interested in text-to-image generation?I am doing my parper on this reasearch too.Could you leave your email?

**Comment by yxh02** [comment]
https://github.com/PKU-ICST-MIPL/Bridge-GAN_TCSVT2019
this is the code for bridge-gan which you didn't link to.

**Comment by Yutong-Zhou-cv** [comment]
> https://github.com/PKU-ICST-MIPL/Bridge-GAN_TCSVT2019
> 
> this is the code for bridge-gan which you didn't link to.

Thank you for your attention. You can find the Email address at the end of this file. Furthermore, thanks for sharing the code of bridge-GAN.  
If you have any further questions or comments, please don’t hesitate to contact me.
Best regards.
